# Generated by Django 4.1.2 on 2023-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_model_delete_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='sgrade',
            field=models.CharField(default='12', max_length=10),
        ),
    ]
