# Generated by Django 4.1.2 on 2023-01-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_model_sgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='scollege_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='sgender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=128),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='sgrade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='slname',
            field=models.CharField(max_length=30),
        ),
    ]
