# Generated by Django 4.1.2 on 2023-01-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_model_scollege_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_model',
            old_name='sid',
            new_name='Sid',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='scollege_name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='scontact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='sgender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='sgrade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='slname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student_model',
            old_name='sname',
            new_name='name',
        ),
    ]
